// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	proto/user.proto

It has these top-level messages:
	User
	CreateRequest
	CreateResponse
	GetRequest
	GetResponse
	FindRequest
	FindResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Sex int32

const (
	Sex_MALE   Sex = 0
	Sex_FEMALE Sex = 1
)

var Sex_name = map[int32]string{
	0: "MALE",
	1: "FEMALE",
}
var Sex_value = map[string]int32{
	"MALE":   0,
	"FEMALE": 1,
}

func (x Sex) String() string {
	return proto.EnumName(Sex_name, int32(x))
}
func (Sex) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Status int32

const (
	Status_OK   Status = 0
	Status_FAIL Status = 1
)

var Status_name = map[int32]string{
	0: "OK",
	1: "FAIL",
}
var Status_value = map[string]int32{
	"OK":   0,
	"FAIL": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type User struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	Sex  Sex    `protobuf:"varint,3,opt,name=sex,enum=user.Sex" json:"sex,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetSex() Sex {
	if m != nil {
		return m.Sex
	}
	return Sex_MALE
}

type CreateRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	Sex  Sex    `protobuf:"varint,3,opt,name=sex,enum=user.Sex" json:"sex,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *CreateRequest) GetSex() Sex {
	if m != nil {
		return m.Sex
	}
	return Sex_MALE
}

type CreateResponse struct {
	Status  Status `protobuf:"varint,1,opt,name=status,enum=user.Status" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *CreateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type FindRequest struct {
	Names []string `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
}

func (m *FindRequest) Reset()                    { *m = FindRequest{} }
func (m *FindRequest) String() string            { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()               {}
func (*FindRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FindRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type FindResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *FindResponse) Reset()                    { *m = FindResponse{} }
func (m *FindResponse) String() string            { return proto.CompactTextString(m) }
func (*FindResponse) ProtoMessage()               {}
func (*FindResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FindResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UpdateRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	Sex  Sex    `protobuf:"varint,3,opt,name=sex,enum=user.Sex" json:"sex,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UpdateRequest) GetSex() Sex {
	if m != nil {
		return m.Sex
	}
	return Sex_MALE
}

type UpdateResponse struct {
	Status  Status `protobuf:"varint,1,opt,name=status,enum=user.Status" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *UpdateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteResponse struct {
	Status  Status `protobuf:"varint,1,opt,name=status,enum=user.Status" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeleteResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *DeleteResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*CreateRequest)(nil), "user.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "user.CreateResponse")
	proto.RegisterType((*GetRequest)(nil), "user.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "user.GetResponse")
	proto.RegisterType((*FindRequest)(nil), "user.FindRequest")
	proto.RegisterType((*FindResponse)(nil), "user.FindResponse")
	proto.RegisterType((*UpdateRequest)(nil), "user.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "user.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "user.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "user.DeleteResponse")
	proto.RegisterEnum("user.Sex", Sex_name, Sex_value)
	proto.RegisterEnum("user.Status", Status_name, Status_value)
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdd, 0x6a, 0xe2, 0x50,
	0x10, 0x36, 0x26, 0x9e, 0xdd, 0x4c, 0x54, 0xb2, 0x67, 0xbd, 0x08, 0x11, 0x96, 0x10, 0xf7, 0x22,
	0x08, 0xba, 0x4b, 0xf2, 0x04, 0xd2, 0xaa, 0x48, 0x2d, 0x2d, 0x47, 0x7c, 0x80, 0xb4, 0x0e, 0x45,
	0xa8, 0x3f, 0xcd, 0x89, 0xc5, 0x37, 0xe8, 0x6b, 0x97, 0xf3, 0x47, 0x4d, 0x2f, 0xbc, 0xca, 0xdd,
	0x9c, 0x99, 0x6f, 0xbe, 0xf9, 0xf8, 0x66, 0x38, 0xe0, 0x1f, 0x8b, 0x43, 0x79, 0xf8, 0x77, 0xe2,
	0x58, 0x8c, 0x65, 0x48, 0x1d, 0x11, 0xc7, 0x0b, 0x70, 0xd6, 0x1c, 0x0b, 0x4a, 0xc1, 0xd9, 0xe7,
	0x3b, 0x0c, 0xac, 0xc8, 0x4a, 0x5c, 0x26, 0x63, 0xea, 0x83, 0x9d, 0xbf, 0x60, 0xd0, 0x8c, 0xac,
	0xa4, 0xc5, 0x44, 0x48, 0xfb, 0x60, 0x73, 0x3c, 0x07, 0x76, 0x64, 0x25, 0xdd, 0xd4, 0x1d, 0x4b,
	0xb6, 0x15, 0x9e, 0x99, 0xc8, 0xc6, 0x0c, 0x3a, 0x37, 0x05, 0xe6, 0x25, 0x32, 0x7c, 0x3b, 0x21,
	0x2f, 0xeb, 0xe0, 0x7c, 0x84, 0xae, 0xe1, 0xe4, 0xc7, 0xc3, 0x9e, 0x23, 0xfd, 0x0b, 0x84, 0x97,
	0x79, 0x79, 0xe2, 0x92, 0xb6, 0x9b, 0xb6, 0x75, 0x87, 0xcc, 0x31, 0x5d, 0xa3, 0x01, 0xfc, 0xd8,
	0x21, 0xe7, 0x66, 0x94, 0xcb, 0xcc, 0x33, 0x8e, 0x00, 0xe6, 0x58, 0x5e, 0x91, 0x18, 0x8f, 0xc0,
	0x93, 0x08, 0x3d, 0xf0, 0x0f, 0x48, 0xa7, 0x24, 0xc4, 0x4b, 0x41, 0x8d, 0x13, 0x9e, 0x31, 0xe5,
	0xe0, 0x00, 0xbc, 0xd9, 0x76, 0xbf, 0x31, 0x8c, 0x3d, 0x68, 0x09, 0x16, 0x21, 0xcf, 0x4e, 0x5c,
	0xa6, 0x1e, 0xf1, 0x7f, 0x68, 0x2b, 0x90, 0x26, 0x8d, 0xa0, 0x25, 0x9a, 0x15, 0xaa, 0xca, 0xaa,
	0x0a, 0xc2, 0xcd, 0xf5, 0x71, 0x53, 0xbb, 0x9b, 0x86, 0xb3, 0x26, 0x37, 0x07, 0xd0, 0xb9, 0xc5,
	0x57, 0xbc, 0xaa, 0x52, 0x8c, 0x35, 0xa0, 0x7a, 0xc6, 0x0e, 0xfb, 0x60, 0xaf, 0xf0, 0x4c, 0x7f,
	0x82, 0x73, 0x3f, 0x59, 0x4e, 0xfd, 0x06, 0x05, 0x20, 0xb3, 0xa9, 0x8c, 0xad, 0x61, 0x08, 0x44,
	0x11, 0x51, 0x02, 0xcd, 0x87, 0x3b, 0xbf, 0x21, 0x70, 0xb3, 0xc9, 0x62, 0xe9, 0x5b, 0xe9, 0x47,
	0x13, 0x3c, 0xe1, 0xf2, 0x0a, 0x8b, 0xf7, 0xed, 0x33, 0xd2, 0x0c, 0x88, 0xba, 0x2f, 0xfa, 0x5b,
	0x49, 0xa8, 0x5c, 0x70, 0xd8, 0xab, 0x26, 0xb5, 0xfa, 0x21, 0xd8, 0x73, 0x2c, 0xa9, 0xaf, 0x8a,
	0x5f, 0xd7, 0x14, 0xfe, 0xba, 0xc8, 0x68, 0xec, 0x08, 0x1c, 0xb1, 0x78, 0xaa, 0x4b, 0x17, 0x97,
	0x12, 0xd2, 0xcb, 0x94, 0x86, 0x67, 0x40, 0xd4, 0x86, 0x8c, 0x9e, 0xca, 0x0d, 0x18, 0x3d, 0xdf,
	0x96, 0x98, 0x01, 0x51, 0xfe, 0x9a, 0xa6, 0xca, 0x4a, 0x4c, 0x53, 0x75, 0x05, 0x4f, 0x44, 0xfe,
	0x02, 0xd9, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x89, 0xcf, 0xee, 0x80, 0x19, 0x04, 0x00, 0x00,
}
